[ADD]feature/cart-CRUD
wecode-bootcamp-korea/37-1st-Just-Do-It-backend pull request #11
Opened 2022-09-24 10:08 UTC by whrod

작성중
CRUD 브랜치 통합

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
작성중

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)

- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)

- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항

- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-09-26 02:34 UTC, Kang-kyunghun requested changes

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/controllers/cartController.js
> +  const { productId, productOptionId, quantity } = req.body;
프론트엔드에서 productOptionId를 모를 것 같은데, update처럼 productId랑 sizeId를 받아야 하지 않을까요?

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/controllers/cartController.js
> +    .send({ message: `Product ${productId} was added to ${userId}'s cart` });
message는 고정적이여야 합니다. 현재는 productID와 userID에 의해 계속 유동적으로 변합니다. 
response에서 특정 값들을 보고 싶다면 아래와 같이 키를 구분해 주세요.
```suggestion
    .send({ message: `Cart was created`, productId : productId, userId: userId });
```

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/controllers/cartController.js
> +  res.status(201).send({ message: `updated ${userId}'s cart` });
- 적절한 status code로 수정해 주세요.
- message도 위의 리뷰 참고해서 수정해 주세요.

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/controllers/cartController.js
> +  const { cartId } = req.body;
delete method는 body가 존재하지 않습니다. 
따라서 path parameter를 활용해서 cartId를 받아 주세요.

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/controllers/cartController.js
> +  res.status(201).send({ message: `deleted ${cartId} cart` });
- 적절한 status code로 수정해 주세요.
- message도 위의 리뷰 참고해서 수정해 주세요.

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/models/cartDao.js
> +  return cart;
다음과 같이 고치는 것이 가독성 측면에서 조금 더 보기 좋아 보입니다.
```suggestion
    SELECT
        c.id AS cartId,
        c.user_id AS userId,
        p.style_code AS styleCode,
        c.quantity,
        c.product_option_id AS productOptionId,
        p.id AS productId,
        p.name AS productName,
        po.size_id AS sizeId,
        s.foot_size AS size,
        po.stock,
        p.retail_price AS retailPrice,
        p.discount_price AS discountPrice,
        p.thumbnail
    FROM carts c
    JOIN product_options po ON po.id = c.product_option_id
    JOIN products p ON po.product_id = p.id
    JOIN sizes s ON po.size_id = s.id
    WHERE  c.user_id = ?
    `,
    [userId]
  );
  return cart;
```

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/models/cartDao.js
> +    )
```suggestion
    INSERT INTO carts (
        product_option_id,
        user_id,
        quantity
    ) VALUE (?, ?, ?)
```

2022-09-26 02:34 UTC, Kang-kyunghun commented on apis/routes/index.js
> +router.use('/cart', cartRouter);
```suggestion
router.use('/carts', cartRouter);
```

2022-09-26 02:36 UTC, Kang-kyunghun commented
1. schema 파일이 올라와 있습니다. 안 올라오게 해주세요.
2. 일단 간단한 수정 사항들 리뷰 드렸습니다. 수정해 주세요.
3. CRUD 전체적으로 Planning 끝나면 같이 보면서 리뷰 해 드리겠습니다.

2022-09-26 03:56 UTC, whrod commented on apis/controllers/cartController.js
> +  const { productId, productOptionId, quantity } = req.body;
상세페이지에서 productOptionId를 프론트에 전달합니다.
상세페이지에서 장바구니에 넣을때에는 productOptionId를 이용하여 넣고,
장바구니 내에서 patch를 할때는 productId, sizeId를 이용하여 productOptionId를 셀렉후 carts를 update합니다.

2022-09-26 11:43 UTC, whrod commented on apis/controllers/cartController.js
> +  const { productId, productOptionId, quantity } = req.body;
구매도 productOptionId로 구매할수 있도록 변경했습니다.

2022-09-26 11:43 UTC, whrod commented on apis/controllers/cartController.js
> +    .send({ message: `Product ${productId} was added to ${userId}'s cart` });
수정완료

2022-09-26 11:43 UTC, whrod commented on apis/controllers/cartController.js
> +  res.status(201).send({ message: `updated ${userId}'s cart` });
수정완료

2022-09-26 11:43 UTC, whrod commented on apis/controllers/cartController.js
> +  const { cartId } = req.body;
수정완료

2022-09-26 11:44 UTC, whrod commented on apis/controllers/cartController.js
> +  res.status(201).send({ message: `deleted ${cartId} cart` });
수정완료

2022-09-26 11:44 UTC, whrod commented on apis/models/cartDao.js
> +  return cart;
수정완료

2022-09-26 11:44 UTC, whrod commented on apis/models/cartDao.js
> +    )
수정완료

2022-09-26 11:44 UTC, whrod commented on apis/routes/index.js
> +router.use('/cart', cartRouter);
수정완료

2022-09-27 07:34 UTC, Kang-kyunghun requested changes

2022-09-27 07:34 UTC, Kang-kyunghun commented on apis/services/cartService.js
> +    return await cartDao.updateQuantityWhenPostCart(
위의 if 조건을 만족 할 경우 return에 의해 함수가 종료 되므로 아래에 else if 보다는 if를 사용하는 것이 조금 더 가독성에 좋습니다.
```suggestion
  }
  
  if (checkIfTheCartExists.productOptionId === parseInt(productOptionId) {
    await checkStock(productOptionId, quantity);

    return await cartDao.updateQuantityWhenPostCart(
```

2022-09-27 08:50 UTC, whrod commented on apis/services/cartService.js
> +    return await cartDao.updateQuantityWhenPostCart(
완료

2022-09-28 01:56 UTC, Kang-kyunghun commented
LGTM!!
리펙토링 관련해서는 내일 한 번 저랑 같이 보겠습니다.

2022-09-28 01:56 UTC, merged