[ADD] feature/product list
wecode-bootcamp-korea/37-1st-Just-Do-It-backend pull request #13
Opened 2022-09-26 05:06 UTC by kyunambae

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 상품 정렬기능 추가( + 페이지네이션 )  
-  쿼리스트링을 이용한 상품 정렬 기능 추가 

- 테스트 방법 :  
/products/  url에 쿼리스트링으로 sort 키를 이용하여 값을 전달
프론트에서 페이지네이션을 하기 때문에 offset 과 limit를  API서버에 전달해줌 
ex) /products/?sort=price+desc&limit=5&offset=0
sort 를 쿼리문에 변수로써 사용하기에 (sortColumn, sortOption) 변수에 if 문으로 적절한 값을 할당

price+desc : 높은 가격순 / sortColumn = price, sortOption = desc
price+asc : 낮은 가격순 / sortColumn = price, sortOption = asc
discountRate+desc : 할인율 순 / sortColumn = discountRate, sortOption = desc
releaseDate+desc : 최신상품 순 / sortColumn = releaseDate, sortOption = desc

else문을 이용하여 디폴트로 최신상품순, 쿼리 결과값을 가지도록 구현
위의 두 변수를 활용하여 order by 절에 구문을 삽입

2. 상품 필터기능 추가
-  상품의 size, brand, color 을 쿼리스트링으로 받음. and or 조건을 이용해서 where절을 적절하게 구성하여 필터링

- 테스트 방법 : 
- /products/?sort=price+desc&limit=5&offset=0&size=240&size=250&size=260&brand=1&brand=2&color=1
필터링 하고싶은 변수(size, brand, color) 를 추가하여 필터링을 수행. 정렬과 섞어서 사용도 가능하며, 정렬의 디폴트는 최신상품 순
size=220~310 까지 5단위, 310~360까지 10단위
color=1~12 까지
brand=1~3 까지

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 고민을 많이 했습니다.

<br />

## :: 기타 질문 및 특이 사항

-

2022-09-27 07:41 UTC, Kang-kyunghun requested changes

2022-09-27 07:41 UTC, Kang-kyunghun commented on apis/models/productDao.js
> +  console.log(statementWhere);
콘솔 지워주세요.

2022-09-27 07:41 UTC, Kang-kyunghun commented on apis/models/productDao.js
> +    SELECT distinct
distinct 사용한 이유를 코멘트로 남겨주세요.

2022-09-27 07:41 UTC, Kang-kyunghun commented on apis/models/productDao.js
> +        1
sizeStock이 0 또는 1의 값만 가지면 되는건가요??

2022-09-27 09:24 UTC, kyunambae commented on apis/models/productDao.js
> +    SELECT distinct
중복을 제거하기 위해서 입니다

2022-09-27 09:25 UTC, kyunambae commented on apis/models/productDao.js
> +        1
삭제 하였습니다

2022-09-27 09:25 UTC, kyunambae commented on apis/models/productDao.js
> +  console.log(statementWhere);
삭제하였습니다

2022-09-28 08:55 UTC, Kang-kyunghun commented
LGTM!! 
고생하셨습니다.

2022-09-28 08:55 UTC, merged