Feature/detail
wecode-bootcamp-korea/37-1st-Just-Do-It-backend pull request #14
Opened 2022-09-26 05:11 UTC by jeongyunah

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

나이키 상세페이지 
(https://www.nike.com/kr/ko_kr/t/men/fw/nike-sportswear/DX9428-100/cwT8pKatbDv/nike-waffle-one-ltr)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- url파라미터 기준으로 제품 데이터를 리턴합니다
- 동일한 제품의 다른 색상들을 상품코드 기준으로 썸네일이미지를 리턴합니다
- 사이즈별 재고는 한번에 보냅니다

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

하나의 페이지에 쿼리문이 6개 들어가는데 더 효율적으로 작성할 수 있는 방법이 있을까요?

2022-09-27 07:55 UTC, Kang-kyunghun requested changes

2022-09-27 07:55 UTC, Kang-kyunghun commented on apis/controllers/productController.js
> +  return res.status(201).json(result)
상태코드 확인해 주세요.

2022-09-27 07:55 UTC, Kang-kyunghun commented on apis/services/productService.js
> +  const [getStyleCode] = await productDao.getStyleCode(productId);
스타일코드만 따로 불러오는 이유가 있나요??

2022-09-27 07:55 UTC, Kang-kyunghun commented on apis/services/productService.js
> +  const styleCodeFront = getStyleCode.style_code.substring(0, 6)
styleCodeFront의 용도가 잘 파악이 안 되네요? 해당 변수의 용도를 코멘트로 남겨주세요~

2022-09-27 07:55 UTC, Kang-kyunghun commented on apis/services/productService.js
> +  const [getDescription] = await productDao.getDescription(productId)
해당 Dao를 하나로 합쳐서 가져와 보시겠어요?

2022-09-27 09:30 UTC, jeongyunah commented on apis/controllers/productController.js
> +  return res.status(201).json(result)
200

2022-09-28 14:02 UTC, jeongyunah commented on apis/services/productService.js
> +  const [getDescription] = await productDao.getDescription(productId)
방금 커밋 했습니다.. 이것이 저의 최선입니다...ㅠ

2022-09-29 12:23 UTC, merged