Feature/signin
wecode-bootcamp-korea/37-1st-Just-Do-It-backend pull request #5
Opened 2022-09-21 18:19 UTC by whrod

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- username, password로 로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인시 아이디 패스워드 keyerror 핸들링
2. 로그인시 아이디 패스워드 정규표현식으로 유효성 검사 => utils/validator.js
3. 로그인 성공시 JWT 토큰 발급
4. 에러핸들링 catchAsync + globalErrorHandler => utils/error.js

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- 정규표현식 관련하여 애를 먹었습니다. 보유한 데이터로 로그인 성공과 실패를 테스트해봤는데 정규표현식을 제대로 작성한지 의문입니다.
- DAO 단에서 ERROR 핸들링이 추가로 필요할지 고민중입니다.

2022-09-22 02:58 UTC, Kang-kyunghun requested changes

2022-09-22 02:58 UTC, Kang-kyunghun commented on db/migrations/20220920090328_create_products_table.sql
>  -- migrate:up
해당 부분은 merge가 되었습니다. 
로컬에서 main pull 받고 해당 branch에서 main merge 후 다시 push 해주세요.

2022-09-22 02:58 UTC, Kang-kyunghun commented on apis/services/userService.js
> +    validatePassword(password);
validate는 회원가입 로직에 있으면 될 것 같습니다.
제거해 주세요.

2022-09-22 02:58 UTC, Kang-kyunghun commented on apis/services/userService.js
> +    const user = await userDao.getUserByUsername(username);
user가 존재하지 않을 경우의 로직도 포함해 주세요.

2022-09-22 02:58 UTC, Kang-kyunghun commented on apis/services/userService.js
> +    console.log(passwordMatch)
console.log는 지워주세요.

2022-09-22 02:58 UTC, Kang-kyunghun commented on apis/services/userService.js
> +        const error = new Error('WRONG_PASSWORD')
로그인 에러처리 시에 ID가 틀렸는지, 비밀번호가 틀렸는지 모르게 하는 것이 좋습니다.
따라서 2개의 에러처리를 모두 같은 메시지로 통일하면 좋습니다.

```suggestion
    if(!passwordMatch) {
        const error = new Error('INVALID_USER')
```

2022-09-22 05:26 UTC, whrod commented on apis/services/userService.js
> +    validatePassword(password);
수정

2022-09-22 05:27 UTC, whrod commented on apis/services/userService.js
> +    console.log(passwordMatch)
수정

2022-09-22 05:32 UTC, whrod commented on apis/services/userService.js
> +        const error = new Error('WRONG_PASSWORD')
수정

2022-09-22 05:46 UTC, whrod commented on apis/services/userService.js
> +    const user = await userDao.getUserByUsername(username);
수정

2022-09-22 06:27 UTC, whrod commented on db/migrations/20220920090328_create_products_table.sql
>  -- migrate:up
넵!

2022-09-22 08:58 UTC, Kang-kyunghun requested changes

2022-09-22 08:58 UTC, Kang-kyunghun commented on apis/models/userDao.js
> +};
서비스 로직에서 처리해 주세요.

2022-09-22 08:58 UTC, Kang-kyunghun commented on apis/models/userDao.js
> +    FROM users
sql문도 줄이 바뀌면 2칸으로 들여쓰기 해주시는 것이 가독성에 더 좋을 것 같습니다.
```suggestion
  const [user] = await database.query(
    `SELECT
        id,
        username,
        fullname,
        password,
        phone_number,
        address,
        gender,
        birth
    FROM users
```

2022-09-22 12:37 UTC, whrod commented on apis/models/userDao.js
> +};
수정

2022-09-22 12:38 UTC, whrod commented on apis/models/userDao.js
> +    FROM users
수정

2022-09-23 01:55 UTC, Kang-kyunghun requested changes

2022-09-23 01:55 UTC, Kang-kyunghun commented on apis/services/userService.js
> +    const error = new Error('USER_NOT_FOUND');
```suggestion
    const error = new Error('INVALID_USER');
```

2022-09-23 01:55 UTC, Kang-kyunghun commented on apis/models/userDao.js
> +    [username]
줄바꿈으로 인한 들여씌기 할 때 2칸 기준을 잘 맞춰주면 가독성에 더 좋습니다.
```suggestion
    SELECT
        id,
        username,
        fullname,
        password,
        phone_number,
        address,
        gender,
        birth
    FROM users
    WHERE username = ?
    `,
    [username]
```

2022-09-23 01:55 UTC, Kang-kyunghun commented on apis/models/userDao.js
> +    FROM users
```suggestion
    `
    SELECT
        id,
        username,
        fullname,
        phone_number,
        address
    FROM users
```

2022-09-23 03:26 UTC, whrod commented on apis/services/userService.js
> +    const error = new Error('USER_NOT_FOUND');
수정

2022-09-23 03:26 UTC, whrod commented on apis/models/userDao.js
> +    [username]
수정

2022-09-23 03:27 UTC, whrod commented on apis/models/userDao.js
> +    FROM users
수정

2022-09-23 04:40 UTC, Kang-kyunghun commented
LGTM

2022-09-23 04:40 UTC, merged